<html xmlns:py="http://genshi.edgewall.org/" xmlns:xi="http://www.w3.org/2001/XInclude" py:strip="">

<py:def function="announcement_id">
PMASA-2015-3
</py:def>

<py:def function="announcement_date">
2015-05-?
</py:def>

<py:def function="announcement_summary">
Vulnerability allowing man-in-the-middle attack on API call to GitHub.
</py:def>

<py:def function="announcement_description">
A vulnerability in the API call to GitHub can be exploited to perform a man-in-the-middle attack.
</py:def>

<py:def function="announcement_severity">
We consider this vulnerability to be serious.
</py:def>

<py:def function="announcement_affected">
Versions 4.0.x (prior to 4.0.10.10), 4.2.x (prior to 4.2.13.3), 4.3.x (prior to 4.3.11.2) and 4.4.x (prior to 4.4.6.1) are affected.
</py:def>

<py:def function="announcement_solution">
Upgrade to phpMyAdmin 4.0.10.10 or newer, or 4.2.13.3 or newer, or 4.3.11.2 or newer, or 4.4.6.1 or newer, or apply the patch listed below.
</py:def>

<py:def function="announcement_references">
Thanks to Maksymilian Arciemowicz of <a href="http://cxsecurity.com">http://cxsecurity.com</a> for reporting this vulnerability.
</py:def>

<py:def function="announcement_cve">CVE-2015-3903</py:def>

<py:def function="announcement_cwe">661 295</py:def>

<py:def function="announcement_commits">
5ebc4daf131dd3bd646326267f3e765d0249bbb4
</py:def>

<py:def function="announcement_commits_4_3">
3739c95118cdf46dd42eb876761654aaafb95cd8
</py:def>

<py:def function="announcement_commits_4_2">
0e18931d9e4b23053285b6fddf3493ca426ff684
</py:def>

<py:def function="announcement_commits_4_0">
e97e7fb0ea2dedfaa95c7dbe872027fb4bd4204c
</py:def>

<xi:include href="_page.tpl" />
</html>
