<!--! Template for security announcement -->
<html xmlns:py="http://genshi.edgewall.org/" xmlns:xi="http://www.w3.org/2001/XInclude" py:strip="">


<py:def function="announcement_id">
PMASA-2011-4
</py:def>

<py:def function="announcement_date">
2011-05-22
</py:def>

<py:def function="announcement_summary">
URL redirection to untrusted site.
</py:def>

<py:def function="announcement_description">
It was possible to redirect to an arbitrary, untrusted site, leading to
a possible phishing attack.
</py:def>

<py:def function="announcement_severity">
We consider this vulnerability to be serious.
</py:def>

<py:def function="announcement_affected">
The 3.4.0 version is affected.
</py:def>

<py:def function="announcement_solution">
Upgrade to phpMyAdmin 3.4.1 or apply the related patch listed below.
</py:def>

<!--! Links to reporter etc, do not forget to escape & to &amp; -->
<py:def function="announcement_references">
This issue was found by Kian Mohageri. 
</py:def>

<!--! CVE ID of the report, this is automatically added to references -->
<py:def function="announcement_cve">CVE-2011-1941</py:def>

<py:def function="announcement_cwe">661 601</py:def>

<py:def function="announcement_commits">
b7a8179eb6bf0f1643970ac57a70b5b513a1cd4f
ecfc8ba4f7b4ea612c58ab5726054ed0f28e200d
</py:def>

<xi:include href="_page.tpl" />
</html>
