<html xmlns:py="http://genshi.edgewall.org/" xmlns:xi="http://www.w3.org/2001/XInclude" py:strip="">

<py:def function="announcement_id">
PMASA-2014-17
</py:def>

<py:def function="announcement_date">
2014-12-?
</py:def>

<py:def function="announcement_summary">
DoS vulnerability with long passwords.
</py:def>

<py:def function="announcement_description">
With very long passwords it was possible to initiate a denial of service attack on phpMyAdmin.
</py:def>

<py:def function="announcement_severity">
We consider this vulnerability to be serious.
</py:def>

<py:def function="announcement_mitigation">
This vulnerability can be mitigated by configuring throttling in the webserver.
</py:def>

<py:def function="announcement_affected">
Versions 4.0.x (prior to 4.0.10.7), 4.1.x (prior to 4.1.14.8) and 4.2.x (prior to 4.2.13.1) are affected.
</py:def>


<py:def function="announcement_solution">
Upgrade to phpMyAdmin 4.0.10.7 or newer, or 4.1.14.8 or newer, or 4.2.13.1 or newer, or apply the patch listed below.
</py:def>

<py:def function="announcement_references">
Thanks to <a href="http://www.behindthefirewalls.com">Javier Nieto</a> and <a href="http://www.devconsole.info">Andres Rojas</a> for reporting this vulnerability.
</py:def>

<py:def function="announcement_cve">CVE-2014-9218</py:def>

<py:def function="announcement_cwe">661 400</py:def>

<py:def function="announcement_commits">
1ac863c7573d12012374d5d41e5c7dc5505ea6e1
</py:def>

<py:def function="announcement_commits_4_1">
62b2c918d26cc78d1763945e3d44d1a63294a819
</py:def>

<py:def function="announcement_commits_4_0">
095729d81205f15f40d216d25917017da4c2fff8
</py:def>

<xi:include href="_page.tpl" />
</html>
